### ISSUE TITLE
Picture resolution loss

### ISSUE THREAD

**Issue by Svetozor1** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#12]
Greetings,

 I am conducting an analysis of alpha-Motoneurons using the AutoNeuriteJ macro. Previously, I used WIS_NeuroMath for this purpose, but I encountered some limitations with that software.

My images have a pixel width of 0.3603 microns. However, AutoNeuriteJ part I rescales the images so that 1 pixel = 1 micron for the skeletonization process in part II compared to the sceletonized pictures of WIS_NeuroMath.

This results in a significant loss of resolution in the skeletonized images. Is there a way to prevent this from happening? For instance, could I keep the “original pixel width” at 1 micron in AutoNeuriteJ part I and then adjust the final results by multiplying them by 0.3603 to preserve the resolution? Or would that compromise the validity of the results? 

I appreciate your response.

Best regards,
Ákos

[The two attached photos show the resolution loss compared to NeuroMath (first screenshot) and the resolution of the sceletonized image in autoneuriteJ when the original pix wdth setting was left at 1. (second screenshot]

![picres](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/assets/135889801/dd1cadcc-9969-4280-b8af-5d761fb4048a)

![picres2](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/assets/135889801/f9a0fa3c-a246-46df-a54a-080d9f3b4a12)

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello Svetozor1,

I think the easiest way to prevent rescaling is when you lunch the part I, the parameter window will ask you the pixel size. Just pretend it's already at 1 um/pxl. The macro might detect that the metadata of the image is not matching this statement and will ask you to reset the metadata. Then pretend again that the pixel size is 1um/pxl. The macro shouldn't rescale the image and you will keep your resolution. 

However please remember that the measurements will be in pxl and you will have to convert the values back if you want them in um. 

Best,
Benoit Boulan
