### ISSUE TITLE
Issue with Part III

### ISSUE THREAD

**Issue by mariajruizest** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#13]
Hi! 
First of all, thank you very much for this useful macro. I want to use it with my data, but first I am trying it with the Demo images. Part I and Part II work fine, but when I try part III, there is an error message about line 926: 

![image](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/assets/144689804/24a89066-efd2-40a4-973e-02de210c7b7b)

Could you help me solving it? Many thanks!

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi Maria, 
To install the macro you need to copy the text file called "neurons.lut" inside the "Luts" folder of Fiji/ImageJ.
This is the function that the macro do not find that is causing this issue. 
You will find some further information in the README file as well as the "step by step protocol" published in this GitHub repository. 

best regards,
Benoit Boulan
