### ISSUE TITLE
Issue in Part 1 and Error Code in Part 2

### ISSUE THREAD

**Issue by rainshine116** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#19]
Hello!
Thank you very much for this macro I have been looking for an automated axon tracer so I am testing this program out. I want to use it with my data, but first, I am trying it with the Demo images. I've been running into a few issues while testing the images. 
Firstly for the demo images when I run Part 1 I get the message: 
Original pixel size do not match with metadata value. Please reset original pixel size in properties.

What do I need to change to fix the pixel size? I tried to just leave the pixel size as is and continue on to Part 2 but then it gave me this error:
Error: Unrecognized command: "BinaryConditionalDilate " in line 370: run ( "BinaryConditionalDilate " , "mask=Binneurons seed=Nuclei  iterations=10 create white" <)> ; 

What should I do to resolve this? Thank you!

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello! 

Pixel size is not really an issue. The macro is simply checking in the metadata if the pixel size match the value you set at the part 1 launching. If not it warns you that there is a mismatch and ask you to "force" changing it or let it as it is. 

fot the Unrecognized command: "BinaryConditionalDilate " I think you didn't install the plugin needed to run the macro. 

Please read carefully the README file ( https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/blob/master/README.md )

Cheers,
Benoit

**Comment by rainshine116** [comment]
Thank you! All of this worked so I was able to finish running the demo images.

**Comment by rainshine116** [comment]
Thank you! I was able to run the demo images. I was wondering if there is a way to make the program Axonal Tree Length and Axonal Tree Branches. When I ran the demo images, there were no values for them in the results.
