### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by jellybellybeans** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#6]
I get the following error in Part 3 of the plug-in: 

Error:		Index (1000) out of 0-5 range in line 1035:
		(called from line 728)
	
		values = split ( lines [ row + 1 <]> , "	" ) ; 

in debug, the variable values are the following: 
lines		array[6]
values		0
coordinates		" 	BX	BY	Width	Height | 1	2	125	1	1 | 2	121	177	1	1 | 3	180	183	1	1 | 4	330	194	1	1 | 5	362...".

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello,
I will need a bit more informations to help you with this issue.
I think the easiest way whould be that you send me the folder with the files named 
Stack_Body, Stack_BodySkelet, Stack_Neuron_Bin, Stack_Neuron_Original and Stack_NoBodySkelet to this email : benoit.boulan@ircm.qc.ca

I will try to run the part 3 and see what happened. 
Please also let me know the parameters you set for the part 3.

Best, 
Benoit
